# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f79fa94057a36ef2198df18ccd371848ef860ab525703da38786e1ce129114bc4195a20daa64326c0145ccb645047b58160f019a3a7720ed3015dbe7ae244a2f

test:
  secret_key_base: d50fce1545e5798a25f8b4f03f42b33eafd596ec60c597f74234fc227032b5b31d1d6418aeffe3f04bf2d45ad3aae688975fafac663883a4509f10ab317241d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
